### ISSUE TITLE
Add column for conjunction and moon age

### ISSUE THREAD

**Issue by hidp123** [crescent-moon-visibility/crescent-moon-visibility#5]
We need to add a column for new moon conjunction time, and another for moon age. Is it possible via the library we are using?

**Comment by ferastemimi** [comment]
Salam alaikum bro, Ramadan Kareem for all...
I hope your are doing well, I'm also looking for a software to generate crescent visibility maps, can you help me in that?
And I need your help, how can I run your software properly, because I tried more time but it was not always working!
Thank you so much, regards...

**Comment by hidp123** [comment]
What issue are you facing?

**Comment by ferastemimi** [comment]
Thank you for your replying:)
After installing "msys2" on my Windows 11 64 bit, then open "msys2", then try to run the program by your command line "./build-mingw.sh", I get this error:

./build-mingw.sh
./build-mingw.sh: line 6: x86_64-w64-mingw32-gcc: command not found

Afterwards, tried to navigate to the program folder path, then inside it, then try to run the program by this command line "bash build-mingw.sh", I get the same error:

bash build-mingw.sh
build-mingw.sh: line 6: x86_64-w64-mingw32-gcc: command not found

Afterwards, tried to use to use "ucrt64.exe" instead of "msys2.exe", the program folder path, then inside it, then try to run the program by this command line "./build-mingw.sh" or the command "bash ./build-mingw.sh", but I never got anything only this "# "!!

However I tried very many times but it never worked for me!
So, please, I need your help to run your program successfully!

Best regards,
Feras Temimi

![UCRT64](https://github.com/crescent-moon-visibility/crescent-moon-visibility/assets/6306600/c28a397d-02bb-4335-822d-0c03311d8129)

**Comment by ferastemimi** [comment]
Dear bro, Thank you for your replying:)
After installing "msys2" on my Windows 11 64 bit, then open "msys2", then try to run the program by your command line "./build-mingw.sh", I get this error:

./build-mingw.sh
./build-mingw.sh: line 6: x86_64-w64-mingw32-gcc: command not found

Afterwards, tried to navigate to the program folder path, then inside it, then try to run the program by this command line "bash build-mingw.sh", I get the same error:

bash build-mingw.sh
build-mingw.sh: line 6: x86_64-w64-mingw32-gcc: command not found

Afterwards, tried to use to use "ucrt64.exe" instead of "msys2.exe", the program folder path, then inside it, then try to run the program by this command line "./build-mingw.sh" or the command "bash ./build-mingw.sh", but I never got anything only this "# "!!

However I tried very many times but it never worked for me!
So, please, I need your help to run your program successfully!

Best Regards,
Feras Temimi

On Wednesday, March 13, 2024 at 07:12:01 AM GMT+3, hidp123 ***@***.***> wrote:  
 
What issue are you facing?
