### ISSUE TITLE
Add "table2" option, and give output at sunset/rise time also, along with "best time".

### ISSUE THREAD

**Issue by hidp123** [crescent-moon-visibility/crescent-moon-visibility#7]
Add "table2" option, and give output at sunset/rise time also, along with "best time".
So two columns for all output, one at "best time" (as it is currently), and second column at "sunset/rise time".

However, there will only be one column for "q code" and "q value", both calculated at "best time" as it is currently.

Example:

Evening (Yallop)&emsp;|&emsp;q value (at BT)&emsp;|&emsp;Moon Az (at BT)&emsp;|&emsp;Moon Az (at SS/SR)&emsp;|&emsp;Moon altitude (at BT)&emsp;|&emsp;Moon&nbsp;altitude&nbsp;(at&nbsp;SS/SR)&emsp;|

**Comment by ferastemimi** [comment]
Salam alaikum bro, Ramadan Kareem for all...
I hope your are doing well, I'm also looking for a software to generate crescent visibility maps, can you help me in that?
And I need your help, how can I run your software properly, because I tried more time but it was not always working!
Thank you so much, regards...
